Project view was added, spaghetti code refactor
manuelsalinas-legion/BTSPocket pull request #8
Opened 2021-05-21 06:08 UTC by cristian-bts

2021-05-27 13:59 UTC, manuelsalinas-legion requested changes
In general good work. You have a good progress now.
We need to discuss some pending tasks

2021-05-27 13:59 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Login/LoginViewController.swift
> +            MessageManager.shared.showBar(title: "Expired session", subtitle: "Your session has expired", type: .info, containsIcon: true, fromBottom: false)
Add in message
**Your session has expired. Please, login again.**

2021-05-27 13:59 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/ProjectsViewController.swift
> +    @IBOutlet weak var tableViewProjects: UITableView!
missing private if needed

2021-05-27 13:59 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/TableViewCells/ProjectTableViewCell.swift
> +    @IBOutlet weak var imageViewProject: UIImageView!
missing private access control for outlets

2021-05-27 13:59 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/TableViewCells/ProjectTableViewCell.swift
> +        self.labelCountUsers.text = countUsersMessage
missing format style via attributedText

**N users** and **you**

2021-05-27 13:59 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Team/TeamViewController.swift
> +    private var refreshControl = UIRefreshControl()
Good. did you add a refresh control and behavior on profile?

2021-05-27 13:59 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Team/TeamViewController.swift
> +        // hacer ternacio a base de mode y eviar a la celda el tipo de usuario que necesita
missing Ternary  way

2021-05-31 14:45 UTC, manuelsalinas-legion commented
**ISSUES DETECTED ON UI**

<img width="930" alt="iPhone_12" src="https://user-images.githubusercontent.com/42077660/120210053-f87c2a80-c1f4-11eb-94ac-bac71d0eb439.png">

2021-05-31 14:57 UTC, manuelsalinas-legion requested changes

2021-05-31 14:57 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/ProjectsViewController.swift
> +                if text.count >= 3 {
Make value 3 into a constant for easy management. 
Sample: 

`let kMinimumCharactersForSearch: Int = 3`

2021-05-31 14:57 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/ProjectsViewController.swift
> +                if text.count < 3 {
Make value 3 into a constant for easy management. 
Sample: 

`let kMinimumCharactersForSearch: Int = 3`

2021-05-31 14:57 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/TableViewCells/ProjectTableViewCell.swift
> +        self.labelNameProject.text = project?.name
capitalized style

2021-05-31 14:57 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Project/TableViewCells/ProjectTableViewCell.swift
> +                                           placeholder: UIImage(named: "placeholderUser"),
I will provide you a placeholder for projects if picture for project is null

2021-05-31 14:57 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Team/TeamViewController.swift
> +enum ReloadType {
Public or private enums?

2021-05-31 14:57 UTC, manuelsalinas-legion commented on BTSPocket/Controllers/Team/TeamViewController.swift
> +enum TeamListStyle {
Public or private enums?

2021-06-03 18:56 UTC, cristian-bts commented on BTSPocket/Controllers/Team/TeamViewController.swift
> +enum ReloadType {
public

2021-06-03 18:56 UTC, cristian-bts commented on BTSPocket/Controllers/Team/TeamViewController.swift
> +enum TeamListStyle {
public

2021-06-04 20:30 UTC, manuelsalinas-legion approved these changes

2021-06-04 20:31 UTC, merged